sudo: false

install: ./install.sh

cache:
  timeout: 1000
  directories:
  - dependencies

script: ./build.sh

addons:
  artifacts:
    paths:
    - build/main.PR.$TRAVIS_PULL_REQUEST.pdf
    debug: true
